alias: New Mail Notify
description: ""
trigger:
  - platform: state
    entity_id: binary_sensor.**YourZigbeeSensor**
    from: "off"
    to: "on"
condition: []
action:
  - service: notify.alexa_media_**YourAmazonEchoDevice**
    data:
      message: >-
        <audio src='https://**your-external-url**/local/mp3/mail.mp3'/>
      data:
        type: tts
  - delay: "00:05:00"
mode: single